const hobbiesArray = [
  { label: "3D printing", value: "3d printing" },
  { label: "Amateur radio", value: "amateur radio" },
  { label: "Scrapbook", value: "scrapbook" },
  { label: "Amateur radio", value: "amateur radio" },
  { label: "Acting", value: "acting" },
  { label: "Baton twirling", value: "baton twirling" },
  { label: "Board games", value: "board games" },
  { label: "Book restoration", value: "book restoration" },
  { label: "Cabaret", value: "cabaret" },
  { label: "Calligraphy", value: "calligraphy" },
  { label: "Candle making", value: "candle making" },
  { label: "Computer programming", value: "computer programming" },
  { label: "Coffee roasting", value: "coffee roasting" },
  { label: "Cooking", value: "cooking" },
  { label: "Colouring", value: "colouring" },
  { label: "Cosplaying", value: "cosplaying" },
  { label: "Couponing", value: "couponing" },
  { label: "Creative writing", value: "creative writing" },
  { label: "Crocheting", value: "crocheting" },
  { label: "Cryptography", value: "cryptography" },
  { label: "Dance", value: "dance" },
  { label: "Digital arts", value: "digital arts" },
  { label: "Drama", value: "drama" },
  { label: "Drawing", value: "drawing" },
  { label: "Do it yourself", value: "do it yourself" },
  { label: "Electronics", value: "electronics" },
  { label: "Embroidery", value: "embroidery" },
  { label: "Fashion", value: "fashion" },
  { label: "Flower arranging", value: "flower arranging" },
  { label: "Foreign language learning", value: "foreign language learning" },
  { label: "Gaming", value: "gaming" },
  { label: "Tabletop games", value: "tabletop games" },
  { label: "Role-playing games", value: "role-playing games" },
  { label: "Gambling", value: "gambling" },
  { label: "Genealogy", value: "genealogy" },
  { label: "Glassblowing", value: "glassblowing" },
  { label: "Gunsmithing", value: "gunsmithing" },
  { label: "Homebrewing", value: "homebrewing" },
  { label: "Ice skating", value: "ice skating" },
  { label: "Jewelry making", value: "jewelry making" },
  { label: "Jigsaw puzzles", value: "jigsaw puzzles" },
  { label: "Juggling", value: "juggling" },
  { label: "Knapping", value: "knapping" },
  { label: "Knitting", value: "knitting" },
  { label: "Kabaddi", value: "kabaddi" },
  { label: "Knife making", value: "knife making" },
  { label: "Lacemaking", value: "lacemaking" },
  { label: "Lapidary", value: "lapidary" },
  { label: "Leather crafting", value: "leather crafting" },
  { label: "Lego building", value: "lego building" },
  { label: "Lockpicking", value: "lockpicking" },
  { label: "Machining", value: "machining" },
  { label: "Macrame", value: "macrame" },
  { label: "Metalworking", value: "metalworking" },
  { label: "Magic", value: "magic" },
  { label: "Model building", value: "model building" },
  { label: "Listening to music", value: "listening to music" },
  { label: "Origami", value: "origami" },
  { label: "Painting", value: "painting" },
  {
    label: "Playing musical instruments",
    value: "playing musical instruments",
  },
  { label: "Pet", value: "pet" },
  { label: "Poi", value: "poi" },
  { label: "Pottery", value: "pottery" },
  { label: "Puzzles", value: "puzzles" },
  { label: "Quilting", value: "quilting" },
  { label: "Reading", value: "reading" },
  { label: "Scrapbooking", value: "scrapbooking" },
  { label: "Sculpting", value: "sculpting" },
  { label: "Sewing", value: "sewing" },
  { label: "Singing", value: "singing" },
  { label: "Sketching", value: "sketching" },
  { label: "Soapmaking", value: "soapmaking" },
  { label: "Sports", value: "sports" },
  { label: "Stand-up comedy", value: "stand-up comedy" },
  { label: "Sudoku", value: "sudoku" },
  { label: "Table tennis", value: "table tennis" },
  { label: "Taxidermy", value: "taxidermy" },
  { label: "Video gaming", value: "video gaming" },
  { label: "Watching movies", value: "watching movies" },
  { label: "Web surfing", value: "web surfing" },
  { label: "Whittling", value: "whittling" },
  { label: "Wood carving", value: "wood carving" },
  { label: "Woodworking", value: "woodworking" },
  { label: "World Building", value: "world building" },
  { label: "Writing", value: "writing" },
  { label: "Yoga", value: "yoga" },
  { label: "Yo-yoing", value: "yo-yoing" },
  { label: "Air sports", value: "air sports" },
  { label: "Archery", value: "archery" },
  { label: "Astronomy", value: "astronomy" },
  { label: "Backpacking", value: "backpacking" },
  { label: "Base jumping", value: "base jumping" },
  { label: "Baseball", value: "baseball" },
  { label: "Basketball", value: "basketball" },
  { label: "Beekeeping", value: "beekeeping" },
  { label: "Bird watching", value: "bird watching" },
  { label: "Blacksmithing", value: "blacksmithing" },
  { label: "Board sports", value: "board sports" },
  { label: "Bodybuilding", value: "bodybuilding" },
  { label: "Brazilian jiu-jitsu", value: "brazilian jiu-jitsu" },
  { label: "Community", value: "community" },
  { label: "Cycling", value: "cycling" },
  { label: "Dowsing", value: "dowsing" },
  { label: "Driving", value: "driving" },
  { label: "Fishing", value: "fishing" },
  { label: "Flag football", value: "flag football" },
  { label: "Flying", value: "flying" },
  { label: "Flying disc", value: "flying disc" },
  { label: "Foraging", value: "foraging" },
  { label: "Gardening", value: "gardening" },
  { label: "Geocaching", value: "geocaching" },
  { label: "Ghost hunting", value: "ghost hunting" },
  { label: "Graffiti", value: "graffiti" },
  { label: "Handball", value: "handball" },
  { label: "Hiking", value: "hiking" },
  { label: "Hooping", value: "hooping" },
  { label: "Horseback riding", value: "horseback riding" },
  { label: "Hunting", value: "hunting" },
  { label: "Inline skating", value: "inline skating" },
  { label: "Jogging", value: "jogging" },
  { label: "Kayaking", value: "kayaking" },
  { label: "Kite flying", value: "kite flying" },
  { label: "Kitesurfing", value: "kitesurfing" },
  { label: "Larping", value: "larping" },
  { label: "Letterboxing", value: "letterboxing" },
  { label: "Metal detecting", value: "metal detecting" },
  { label: "Motor sports", value: "motor sports" },
  { label: "Mountain biking", value: "mountain biking" },
  { label: "Mountaineering", value: "mountaineering" },
  { label: "Mushroom hunting", value: "mushroom hunting" },
  { label: "Mycology", value: "mycology" },
  { label: "Netball", value: "netball" },
  { label: "Nordic skating", value: "nordic skating" },
  { label: "Orienteering", value: "orienteering" },
  { label: "Paintball", value: "paintball" },
  { label: "Parkour", value: "parkour" },
  { label: "Photography", value: "photography" },
  { label: "Polo", value: "polo" },
  { label: "Rafting", value: "rafting" },
  { label: "Rappelling", value: "rappelling" },
  { label: "Rock climbing", value: "rock climbing" },
  { label: "Roller skating", value: "roller skating" },
  { label: "Rugby", value: "rugby" },
  { label: "Running", value: "running" },
  { label: "Sailing", value: "sailing" },
  { label: "Sand art", value: "sand art" },
  { label: "Scouting", value: "scouting" },
  { label: "Scuba diving", value: "scuba diving" },
  { label: "Sculling", value: "sculling" },
  { label: "Rowing", value: "rowing" },
  { label: "Shooting", value: "shooting" },
  { label: "Shopping", value: "shopping" },
  { label: "Skateboarding", value: "skateboarding" },
  { label: "Skiing", value: "skiing" },
  { label: "Skim Boarding", value: "skim boarding" },
  { label: "Skydiving", value: "skydiving" },
  { label: "Slacklining", value: "slacklining" },
  { label: "Snowboarding", value: "snowboarding" },
  { label: "Stone skipping", value: "stone skipping" },
  { label: "Surfing", value: "surfing" },
  { label: "Swimming", value: "swimming" },
  { label: "Taekwondo", value: "taekwondo" },
  { label: "Tai chi", value: "tai chi" },
  { label: "Urban exploration", value: "urban exploration" },
  { label: "Vacation", value: "vacation" },
  { label: "Vehicle restoration", value: "vehicle restoration" },
  { label: "Water sports", value: "water sports" },
];

export default hobbiesArray;
