const professionArray = [
  { label: "Academic librarian", value: "academic librarian" },
  { label: "Accountant", value: "accountant" },
  { label: "Accounting technician", value: "accounting technician" },
  { label: "Actuary", value: "actuary" },
  { label: "Adult nurse", value: "adult nurse" },
  {
    label: "Advertising account executive",
    value: "advertising account executive",
  },
  {
    label: "Advertising account planner",
    value: "advertising account planner",
  },
  { label: "Advertising copywriter", value: "advertising copywriter" },
  { label: "Advice worker", value: "advice worker" },
  { label: "Advocate (Scotland)", value: "advocate (scotland)" },
  { label: "Aeronautical engineer", value: "aeronautical engineer" },
  { label: "Agricultural consultant", value: "agricultural consultant" },
  { label: "Agricultural manager", value: "agricultural manager" },
  {
    label: "Aid worker/humanitarian worker",
    value: "aid worker/humanitarian worker",
  },
  { label: "Air traffic controller", value: "air traffic controller" },
  { label: "Airline cabin crew", value: "airline cabin crew" },
  { label: "Amenity horticulturist", value: "amenity horticulturist" },
  { label: "Analytical chemist", value: "analytical chemist" },
  { label: "Animal nutritionist", value: "animal nutritionist" },
  { label: "Animator", value: "animator" },
  { label: "Archaeologist", value: "archaeologist" },
  { label: "Architect", value: "architect" },
  { label: "Architectural technologist", value: "architectural technologist" },
  { label: "Archivist", value: "archivist" },
  { label: "Armed forces officer", value: "armed forces officer" },
  { label: "Aromatherapist", value: "aromatherapist" },
  { label: "Art therapist", value: "art therapist" },
  { label: "Arts administrator", value: "arts administrator" },
  { label: "Auditor", value: "auditor" },
  { label: "Automotive engineer", value: "automotive engineer" },
  { label: "Barrister", value: "barrister" },
  { label: "Barrister’s clerk", value: "barrister’s clerk" },
  { label: "Bilingual secretary", value: "bilingual secretary" },
  { label: "Biomedical engineer", value: "biomedical engineer" },
  { label: "Biomedical scientist", value: "biomedical scientist" },
  { label: "Biotechnologist", value: "biotechnologist" },
  { label: "Brand manager", value: "brand manager" },
  { label: "Broadcasting presenter", value: "broadcasting presenter" },
  {
    label: "Building control officer/surveyor",
    value: "building control officer/surveyor",
  },
  { label: "Building services engineer", value: "building services engineer" },
  { label: "Building surveyor", value: "building surveyor" },
  { label: "Camera operator", value: "camera operator" },
  {
    label: "Careers adviser (higher education)",
    value: "careers adviser (higher education)",
  },
  { label: "Careers adviser", value: "careers adviser" },
  { label: "Careers consultant", value: "careers consultant" },
  { label: "Cartographer", value: "cartographer" },
  { label: "Catering manager", value: "catering manager" },
  { label: "Charities administrator", value: "charities administrator" },
  { label: "Charities fundraiser", value: "charities fundraiser" },
  {
    label: "Chemical (process) engineer",
    value: "chemical (process) engineer",
  },
  { label: "Child psychotherapist", value: "child psychotherapist" },
  { label: "Children's nurse", value: "children's nurse" },
  { label: "Chiropractor", value: "chiropractor" },
  { label: "Civil engineer", value: "civil engineer" },
  {
    label: "Civil Service administrator",
    value: "civil service administrator",
  },
  { label: "Clinical biochemist", value: "clinical biochemist" },
  { label: "Clinical cytogeneticist", value: "clinical cytogeneticist" },
  { label: "Clinical microbiologist", value: "clinical microbiologist" },
  {
    label: "Clinical molecular geneticist",
    value: "clinical molecular geneticist",
  },
  {
    label: "Clinical research associate",
    value: "clinical research associate",
  },
  {
    label: "Clinical scientist - tissue typing",
    value: "clinical scientist - tissue typing",
  },
  {
    label: "Clothing and textile technologist",
    value: "clothing and textile technologist",
  },
  { label: "Colour technologist", value: "colour technologist" },
  { label: "Commercial horticulturist", value: "commercial horticulturist" },
  {
    label: "Commercial/residential/rural surveyor",
    value: "commercial/residential/rural surveyor",
  },
  { label: "Commissioning editor", value: "commissioning editor" },
  { label: "Commissioning engineer", value: "commissioning engineer" },
  { label: "Commodity broker", value: "commodity broker" },
  { label: "Communications engineer", value: "communications engineer" },
  { label: "Community arts worker", value: "community arts worker" },
  {
    label: "Community education officer",
    value: "community education officer",
  },
  { label: "Community worker", value: "community worker" },
  { label: "Company secretary", value: "company secretary" },
  { label: "Computer sales support", value: "computer sales support" },
  { label: "Computer scientist", value: "computer scientist" },
  { label: "Conference organiser", value: "conference organiser" },
  { label: "Consultant", value: "consultant" },
  { label: "Consumer rights adviser", value: "consumer rights adviser" },
  {
    label: "Control and instrumentation engineer",
    value: "control and instrumentation engineer",
  },
  { label: "Corporate banker", value: "corporate banker" },
  { label: "Corporate treasurer", value: "corporate treasurer" },
  { label: "Counsellor", value: "counsellor" },
  { label: "Courier/tour guide", value: "courier/tour guide" },
  {
    label: "Court reporter/verbatim reporter",
    value: "court reporter/verbatim reporter",
  },
  { label: "Credit analyst", value: "credit analyst" },
  {
    label: "Crown Prosecution Service lawyer",
    value: "crown prosecution service lawyer",
  },
  { label: "Crystallographer", value: "crystallographer" },
  { label: "Curator", value: "curator" },
  { label: "Customs officer", value: "customs officer" },
  { label: "Cyber security specialist", value: "cyber security specialist" },
  { label: "Dance movement therapist", value: "dance movement therapist" },
  { label: "Data analyst", value: "data analyst" },
  { label: "Data scientist", value: "data scientist" },
  { label: "Data visualisation analyst", value: "data visualisation analyst" },
  { label: "Database administrator", value: "database administrator" },
  { label: "Debt/finance adviser", value: "debt/finance adviser" },
  { label: "Dental hygienist", value: "dental hygienist" },
  { label: "Dentist", value: "dentist" },
  { label: "Design engineer", value: "design engineer" },
  { label: "Dietitian", value: "dietitian" },
  { label: "Diplomatic service", value: "diplomatic service" },
  {
    label: "Doctor (general practitioner, GP)",
    value: "doctor (general practitioner, gp)",
  },
  { label: "Doctor (hospital)", value: "doctor (hospital)" },
  { label: "Dramatherapist", value: "dramatherapist" },
  { label: "Economist", value: "economist" },
  { label: "Editorial assistant", value: "editorial assistant" },
  { label: "Education administrator", value: "education administrator" },
  { label: "Electrical engineer", value: "electrical engineer" },
  { label: "Electronics engineer", value: "electronics engineer" },
  { label: "Employment advice worker", value: "employment advice worker" },
  {
    label: "Energy conservation officer",
    value: "energy conservation officer",
  },
  { label: "Engineering geologist", value: "engineering geologist" },
  {
    label: "Environmental education officer",
    value: "environmental education officer",
  },
  {
    label: "Environmental health officer",
    value: "environmental health officer",
  },
  { label: "Environmental manager", value: "environmental manager" },
  { label: "Environmental scientist", value: "environmental scientist" },
  {
    label: "Equal opportunities officer",
    value: "equal opportunities officer",
  },
  {
    label: "Equality and diversity officer",
    value: "equality and diversity officer",
  },
  { label: "Ergonomist", value: "ergonomist" },
  { label: "Estate agent", value: "estate agent" },
  {
    label: "European Commission administrators",
    value: "european commission administrators",
  },
  {
    label: "Exhibition display designer",
    value: "exhibition display designer",
  },
  { label: "Exhibition organiser", value: "exhibition organiser" },
  { label: "Exploration geologist", value: "exploration geologist" },
  { label: "Facilities manager", value: "facilities manager" },
  { label: "Field trials officer", value: "field trials officer" },
  { label: "Financial manager", value: "financial manager" },
  { label: "Firefighter", value: "firefighter" },
  { label: "Fisheries officer", value: "fisheries officer" },
  { label: "Fitness centre manager", value: "fitness centre manager" },
  { label: "Food scientist", value: "food scientist" },
  { label: "Food technologist", value: "food technologist" },
  { label: "Forensic scientist", value: "forensic scientist" },
  { label: "Geneticist", value: "geneticist" },
  {
    label: "Geographical information systems manager",
    value: "geographical information systems manager",
  },
  { label: "Geomatics/land surveyor", value: "geomatics/land surveyor" },
  { label: "Government lawyer", value: "government lawyer" },
  {
    label: "Government research officer",
    value: "government research officer",
  },
  { label: "Graphic designer", value: "graphic designer" },
  { label: "Health and safety adviser", value: "health and safety adviser" },
  {
    label: "Health and safety inspector",
    value: "health and safety inspector",
  },
  {
    label: "Health promotion specialist",
    value: "health promotion specialist",
  },
  { label: "Health service manager", value: "health service manager" },
  { label: "Health visitor", value: "health visitor" },
  { label: "Herbalist", value: "herbalist" },
  { label: "Heritage manager", value: "heritage manager" },
  {
    label: "Higher education administrator",
    value: "higher education administrator",
  },
  {
    label: "Higher education advice worker",
    value: "higher education advice worker",
  },
  { label: "Homeless worker", value: "homeless worker" },
  { label: "Horticultural consultant", value: "horticultural consultant" },
  { label: "Hotel manager", value: "hotel manager" },
  { label: "Housing adviser", value: "housing adviser" },
  { label: "Human resources officer", value: "human resources officer" },
  { label: "Hydrologist", value: "hydrologist" },
  { label: "Illustrator", value: "illustrator" },
  { label: "Immigration officer", value: "immigration officer" },
  { label: "Immunologist", value: "immunologist" },
  {
    label: "Industrial/product designer",
    value: "industrial/product designer",
  },
  { label: "Information scientist", value: "information scientist" },
  {
    label: "Information systems manager",
    value: "information systems manager",
  },
  {
    label: "Information technology/software trainers",
    value: "information technology/software trainers",
  },
  { label: "Insurance broker", value: "insurance broker" },
  { label: "Insurance claims inspector", value: "insurance claims inspector" },
  { label: "Insurance risk surveyor", value: "insurance risk surveyor" },
  { label: "Insurance underwriter", value: "insurance underwriter" },
  { label: "Interpreter", value: "interpreter" },
  { label: "Investment analyst", value: "investment analyst" },
  {
    label: "Investment banker - corporate finance",
    value: "investment banker - corporate finance",
  },
  {
    label: "Investment banker – operations",
    value: "investment banker – operations",
  },
  { label: "Investment fund manager", value: "investment fund manager" },
  { label: "IT consultant", value: "it consultant" },
  { label: "IT support analyst", value: "it support analyst" },
  { label: "Journalist", value: "journalist" },
  { label: "Laboratory technician", value: "laboratory technician" },
  { label: "Land-based engineer", value: "land-based engineer" },
  { label: "Landscape architect", value: "landscape architect" },
  { label: "Learning disability nurse", value: "learning disability nurse" },
  { label: "Learning mentor", value: "learning mentor" },
  { label: "Lecturer (adult education)", value: "lecturer (adult education)" },
  {
    label: "Lecturer (further education)",
    value: "lecturer (further education)",
  },
  {
    label: "Lecturer (higher education)",
    value: "lecturer (higher education)",
  },
  { label: "Legal executive", value: "legal executive" },
  { label: "Leisure centre manager", value: "leisure centre manager" },
  { label: "Licensed conveyancer", value: "licensed conveyancer" },
  {
    label: "Local government administrator",
    value: "local government administrator",
  },
  { label: "Local government lawyer", value: "local government lawyer" },
  {
    label: "Logistics/distribution manager",
    value: "logistics/distribution manager",
  },
  { label: "Magazine features editor", value: "magazine features editor" },
  { label: "Magazine journalist", value: "magazine journalist" },
  { label: "Maintenance engineer", value: "maintenance engineer" },
  { label: "Management accountant", value: "management accountant" },
  { label: "Manufacturing engineer", value: "manufacturing engineer" },
  {
    label: "Manufacturing machine operator",
    value: "manufacturing machine operator",
  },
  { label: "Manufacturing toolmaker", value: "manufacturing toolmaker" },
  { label: "Marine scientist", value: "marine scientist" },
  { label: "Market research analyst", value: "market research analyst" },
  { label: "Market research executive", value: "market research executive" },
  { label: "Marketing account manager", value: "marketing account manager" },
  { label: "Marketing assistant", value: "marketing assistant" },
  { label: "Marketing executive", value: "marketing executive" },
  {
    label: "Marketing manager (social media)",
    value: "marketing manager (social media)",
  },
  { label: "Materials engineer", value: "materials engineer" },
  { label: "Materials specialist", value: "materials specialist" },
  { label: "Mechanical engineer", value: "mechanical engineer" },
  { label: "Media analyst", value: "media analyst" },
  { label: "Media buyer", value: "media buyer" },
  { label: "Media planner", value: "media planner" },
  { label: "Medical physicist", value: "medical physicist" },
  { label: "Medical representative", value: "medical representative" },
  { label: "Mental health nurse", value: "mental health nurse" },
  { label: "Metallurgist", value: "metallurgist" },
  { label: "Meteorologist", value: "meteorologist" },
  { label: "Microbiologist", value: "microbiologist" },
  { label: "Midwife", value: "midwife" },
  { label: "Mining engineer", value: "mining engineer" },
  { label: "Mobile developer", value: "mobile developer" },
  { label: "Multimedia programmer", value: "multimedia programmer" },
  { label: "Multimedia specialists", value: "multimedia specialists" },
  { label: "Museum education officer", value: "museum education officer" },
  {
    label: "Museum/gallery exhibition officer",
    value: "museum/gallery exhibition officer",
  },
  { label: "Music therapist", value: "music therapist" },
  { label: "Nanoscientist", value: "nanoscientist" },
  {
    label: "Nature conservation officer",
    value: "nature conservation officer",
  },
  { label: "Naval architect", value: "naval architect" },
  { label: "Network administrator", value: "network administrator" },
  { label: "Nurse", value: "nurse" },
  { label: "Nutritional therapist", value: "nutritional therapist" },
  { label: "Nutritionist", value: "nutritionist" },
  { label: "Occupational therapist", value: "occupational therapist" },
  { label: "Oceanographer", value: "oceanographer" },
  { label: "Office manager", value: "office manager" },
  { label: "Operational researcher", value: "operational researcher" },
  { label: "Orthoptist", value: "orthoptist" },
  { label: "Outdoor pursuits manager", value: "outdoor pursuits manager" },
  { label: "Packaging technologist", value: "packaging technologist" },
  { label: "Paediatric nurse", value: "paediatric nurse" },
  { label: "Paramedic", value: "paramedic" },
  { label: "Patent attorney", value: "patent attorney" },
  { label: "Patent examiner", value: "patent examiner" },
  { label: "Pension scheme manager", value: "pension scheme manager" },
  { label: "Personal assistant", value: "personal assistant" },
  { label: "Petroleum engineer", value: "petroleum engineer" },
  { label: "Pharmacist", value: "pharmacist" },
  { label: "Pharmacologist", value: "pharmacologist" },
  { label: "Pharmacovigilance officer", value: "pharmacovigilance officer" },
  { label: "Photographer", value: "photographer" },
  { label: "Physiotherapist", value: "physiotherapist" },
  { label: "Picture researcher", value: "picture researcher" },
  {
    label: "Planning and development surveyor",
    value: "planning and development surveyor",
  },
  { label: "Planning technician", value: "planning technician" },
  { label: "Plant breeder", value: "plant breeder" },
  { label: "Police officer", value: "police officer" },
  { label: "Political party agent", value: "political party agent" },
  {
    label: "Political party research officer",
    value: "political party research officer",
  },
  { label: "Practice nurse", value: "practice nurse" },
  { label: "Press photographer", value: "press photographer" },
  { label: "Press sub-editor", value: "press sub-editor" },
  { label: "Prison officer", value: "prison officer" },
  { label: "Private music teacher", value: "private music teacher" },
  { label: "Probation officer", value: "probation officer" },
  {
    label: "Product development scientist",
    value: "product development scientist",
  },
  { label: "Production manager", value: "production manager" },
  { label: "Programme researcher", value: "programme researcher" },
  { label: "Project manager", value: "project manager" },
  { label: "Psychologist (clinical)", value: "psychologist (clinical)" },
  { label: "Psychologist (educational)", value: "psychologist (educational)" },
  { label: "Psychotherapist", value: "psychotherapist" },
  {
    label: "Public affairs consultant (lobbyist)",
    value: "public affairs consultant (lobbyist)",
  },
  {
    label: "Public affairs consultant (research)",
    value: "public affairs consultant (research)",
  },
  { label: "Public house manager", value: "public house manager" },
  { label: "Public librarian", value: "public librarian" },
  {
    label: "Public relations (PR) officer",
    value: "public relations (pr) officer",
  },
  { label: "QA analyst", value: "qa analyst" },
  { label: "Quality assurance manager", value: "quality assurance manager" },
  { label: "Quantity surveyor", value: "quantity surveyor" },
  { label: "Records manager", value: "records manager" },
  { label: "Recruitment consultant", value: "recruitment consultant" },
  { label: "Recycling officer", value: "recycling officer" },
  { label: "Regulatory affairs officer", value: "regulatory affairs officer" },
  { label: "Research chemist", value: "research chemist" },
  { label: "Research scientist", value: "research scientist" },
  { label: "Restaurant manager", value: "restaurant manager" },
  { label: "Retail banker", value: "retail banker" },
  { label: "Retail buyer", value: "retail buyer" },
  { label: "Retail manager", value: "retail manager" },
  { label: "Retail merchandiser", value: "retail merchandiser" },
  { label: "Retail pharmacist", value: "retail pharmacist" },
  { label: "Sales executive", value: "sales executive" },
  { label: "Sales manager", value: "sales manager" },
  { label: "Scene of crime officer", value: "scene of crime officer" },
  { label: "Secretary", value: "secretary" },
  { label: "Seismic interpreter", value: "seismic interpreter" },
  { label: "Site engineer", value: "site engineer" },
  { label: "Site manager", value: "site manager" },
  { label: "Social researcher", value: "social researcher" },
  { label: "Social worker", value: "social worker" },
  { label: "Software developer", value: "software developer" },
  { label: "Soil scientist", value: "soil scientist" },
  { label: "Solicitor", value: "solicitor" },
  {
    label: "Speech and language therapist",
    value: "speech and language therapist",
  },
  { label: "Sports coach", value: "sports coach" },
  { label: "Sports development officer", value: "sports development officer" },
  { label: "Sports therapist", value: "sports therapist" },
  { label: "Statistician", value: "statistician" },
  { label: "Stockbroker", value: "stockbroker" },
  { label: "Structural engineer", value: "structural engineer" },
  { label: "Student", value: "student" },
  { label: "Systems analyst", value: "systems analyst" },
  { label: "Systems developer", value: "systems developer" },
  { label: "Tax inspector", value: "tax inspector" },
  {
    label: "Teacher (nursery/early years)",
    value: "teacher (nursery/early years)",
  },
  { label: "Teacher (primary)", value: "teacher (primary)" },
  { label: "Teacher (secondary)", value: "teacher (secondary)" },
  {
    label: "Teacher (special educational needs)",
    value: "teacher (special educational needs)",
  },
  {
    label: "Teaching/classroom assistant",
    value: "teaching/classroom assistant",
  },
  { label: "Technical author", value: "technical author" },
  { label: "Technical sales engineer", value: "technical sales engineer" },
  { label: "TEFL/TESL teacher", value: "tefl/tesl teacher" },
  {
    label: "Television production assistant",
    value: "television production assistant",
  },
  { label: "Test automation developer", value: "test automation developer" },
  { label: "Tour operator", value: "tour operator" },
  { label: "Tourism officer", value: "tourism officer" },
  {
    label: "Tourist information manager",
    value: "tourist information manager",
  },
  { label: "Town and country planner", value: "town and country planner" },
  { label: "Toxicologist", value: "toxicologist" },
  {
    label: "Trade union research officer",
    value: "trade union research officer",
  },
  { label: "Trader", value: "trader" },
  { label: "Trading standards officer", value: "trading standards officer" },
  {
    label: "Training and development officer",
    value: "training and development officer",
  },
  { label: "Translator", value: "translator" },
  { label: "Transportation planner", value: "transportation planner" },
  { label: "Travel agent", value: "travel agent" },
  {
    label: "TV/film/theatre set designer",
    value: "tv/film/theatre set designer",
  },
  { label: "UX designer", value: "ux designer" },
  { label: "Validation engineer", value: "validation engineer" },
  { label: "Veterinary nurse", value: "veterinary nurse" },
  { label: "Veterinary surgeon", value: "veterinary surgeon" },
  { label: "Video game designer", value: "video game designer" },
  { label: "Video game developer", value: "video game developer" },
  { label: "Volunteer work organiser", value: "volunteer work organiser" },
  { label: "Warehouse manager", value: "warehouse manager" },
  { label: "Waste disposal officer", value: "waste disposal officer" },
  { label: "Water conservation officer", value: "water conservation officer" },
  { label: "Water engineer", value: "water engineer" },
  { label: "Web designer", value: "web designer" },
  { label: "Web developer", value: "web developer" },
  { label: "Welfare rights adviser", value: "welfare rights adviser" },
  { label: "Writer", value: "writer" },
  { label: "Youth worker", value: "youth worker" },
];

export default professionArray;
