const statesArray = [
  { label: "Andhra Pradesh", value: "andhra pradesh" },
  { label: "Arunachal Pradesh", value: "arunachal pradesh" },
  { label: "Assam", value: "assam" },
  { label: "Bihar", value: "bihar" },
  { label: "Chhattisgarh", value: "chhattisgarh" },
  { label: "Goa", value: "goa" },
  { label: "Gujarat", value: "gujarat" },
  { label: "Haryana", value: "haryana" },
  { label: "Himachal Pradesh", value: "himachal pradesh" },
  { label: "Jammu and Kashmir", value: "jammu and kashmir" },
  { label: "Jharkhand", value: "jharkhand" },
  { label: "Karnataka", value: "karnataka" },
  { label: "Kerala", value: "kerala" },
  { label: "Madhya Pradesh", value: "madhya pradesh" },
  { label: "Maharashtra", value: "maharashtra" },
  { label: "Manipur", value: "manipur" },
  { label: "Meghalaya", value: "meghalaya" },
  { label: "Mizoram", value: "mizoram" },
  { label: "Nagaland", value: "nagaland" },
  { label: "Odisha", value: "odisha" },
  { label: "Punjab", value: "punjab" },
  { label: "Rajasthan", value: "rajasthan" },
  { label: "Sikkim", value: "sikkim" },
  { label: "Tamil Nadu", value: "tamil nadu" },
  { label: "Telangana", value: "telangana" },
  { label: "Tripura", value: "tripura" },
  { label: "Uttarakhand", value: "uttarakhand" },
  { label: "Uttar Pradesh", value: "uttar pradesh" },
  { label: "West Bengal", value: "west bengal" },
  {
    label: "Andaman and Nicobar Islands",
    value: "andaman and nicobar islands",
  },
  { label: "Chandigarh", value: "chandigarh" },
  { label: "Dadra and Nagar Haveli", value: "dadra and nagar haveli" },
  { label: "Daman and Diu", value: "daman and diu" },
  { label: "Delhi", value: "delhi" },
  { label: "Lakshadweep", value: "lakshadweep" },
  { label: "Puducherry", value: "puducherry" },
];

export default statesArray;
